#!/usr/bin/perl -w
#
#------------------------------------------------------------------
#   
#     running a list of problems 
#     j-l morales  
#     ITAM   2015
#
#------------------------------------------------------------------
#
#
use FileHandle;
use IPC::Open2;

$filename = "LIST_small";
 
  open LIST, $filename or die "Couldn't open file $filename\n";

#     Now read and process one line at a time
#------------------
  $pid = open2(*RESPONSE, *MATLAB,"matlab -nojvm");
  $pid or die;
#------------------
while( <LIST> )
{
    chomp;
    if ( $_ eq "" ) { print "\n   *** End of the list *** \n"; last; }
#
    @names = split;
    $name = shift @names;
    print "  Processing $name  \n";
        
    print MATLAB &q(<<"    ENDMATLAB");
    : path(path,'/Users/jmorales/bin');
    : m = 10; TOL = 1.0e-5; maxiter = 1000;
    : [x, norm_g, niter] = LBFGS ( '$name', m, TOL, maxiter );
    : 
    : disp( 'Next problem' );
    :
    ENDMATLAB

    while( $got = <RESPONSE> ) {
	last if $got =~ /Next problem/;
    }
        
    system("mv $name.out $RESJ/$name.out");
    system("rm $name.nl");

#----
}    

close MATLAB or die $!;
close RESPONSE or die $!;
close LIST or die $!;
#                            

sub q{
    my $string  = $_[0];
    $string =~ s/^\s*://gm;
    #$string =~ s{ (.*)\*/\s*$ }{ sprintf "%-73s*/\n", $1 }gmex;
    
    return $string;
}
